.DEFAULT_GOAL := help
SHELL := /bin/bash

DBT := uv run dbt
DBT_DIRS := --project-dir dbt --profiles-dir dbt
TARGET ?= dev

# Load .env if present so DUCKDB_PATH / GCP vars are available.
ifneq (,$(wildcard .env))
include .env
export
endif

.PHONY: help install data deps build build-full run test seed docs freshness lint fix dag-test verify clean \
        governance-apply governance-build governance-validate governance-plan governance-destroy \
        dq-report contracts-check spark-test spark-validate topics-check metrics bq-data verify-cloud \
        privacy-test erasure-check erasure-deadlines erasure-sweep lineage-check

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

install: ## Create the uv venv (Python 3.12) and install the dev dependency group
	uv sync

data: ## Generate synthetic raw data into the local DuckDB file
	uv run python scripts/generate_test_data.py --target duckdb

deps: ## Install dbt packages (dbt_utils, dbt_expectations, elementary, codegen)
	$(DBT) deps $(DBT_DIRS)

build: ## Run + test everything (dbt build) against $(TARGET)
	$(DBT) build $(DBT_DIRS) --target $(TARGET)

run: ## Run models only against $(TARGET)
	$(DBT) run $(DBT_DIRS) --target $(TARGET)

test: ## Run dbt tests against $(TARGET)
	$(DBT) test $(DBT_DIRS) --target $(TARGET)

seed: ## Load CSV seeds against $(TARGET)
	$(DBT) seed $(DBT_DIRS) --target $(TARGET)

freshness: ## Check source freshness against $(TARGET)
	$(DBT) source freshness $(DBT_DIRS) --target $(TARGET)

docs: ## Generate and serve dbt docs (Ctrl-C to stop)
	$(DBT) docs generate $(DBT_DIRS) --target $(TARGET)
	$(DBT) docs serve $(DBT_DIRS)

lint: ## Lint SQL models with SQLFluff
	uv run sqlfluff lint dbt/models

fix: ## Auto-fix SQL models with SQLFluff
	uv run sqlfluff fix dbt/models

dag-test: ## Parse/AST-check every DAG file (no Airflow install needed)
	uv run python tests/check_dags_compile.py

verify: deps data build-full freshness lint ## Full local verification pipeline (DuckDB)
	@echo "Local verification complete."

build-full: ## dbt build, rebuilding incremental models from scratch
	# `make data` regenerates the raw tables over a NEW date window, so incremental marts still hold
	# rows for user_ids that no longer exist upstream -- which fails the relationships test. A
	# from-scratch verification has to rebuild from scratch; anything else tests stale state.
	#
	# NOTE: `--full-refresh` alone is NOT enough. The marts set `full_refresh=false` in config
	# (guarding production against an accidental rebuild of a large partitioned table), and a config
	# value of false OVERRIDES the CLI flag. The repo's own `force_full_refresh` var is the intended
	# way in, so pass both: the var to permit it, the flag to request it.
	$(DBT) build $(DBT_DIRS) --target $(TARGET) --full-refresh --vars '{force_full_refresh: true}' 

# ---------------------------------------------------------------------------------------------
# GCP: governance, data quality, and the cloud-side pipeline.
#
# GOVERNANCE_VARS is the Terraform -> dbt handoff. Policy tag ids and row-access grantees are
# generated by Terraform and injected here, so no model file contains an environment-specific id.
# ---------------------------------------------------------------------------------------------
TF_DIR := terraform/envs/dev
GOVERNANCE_VARS = $(shell uv run python scripts/governance_vars.py --tf-dir $(TF_DIR))

governance-plan: ## Terraform plan for the governance + lakehouse stack
	cd $(TF_DIR) && terraform init -input=false && terraform plan -input=false

governance-apply: ## Terraform apply: datasets, taxonomy, policy tags, personas, Dataplex scans
	cd $(TF_DIR) && terraform init -input=false && terraform apply -input=false

bq-data: ## Load synthetic raw data into the BigQuery Bronze dataset
	uv run python scripts/generate_test_data.py --target bigquery --clients 800 --days 30

governance-build: ## dbt build on BigQuery with policy tags + row access policies applied
	$(DBT) build $(DBT_DIRS) --target prod --vars '$(GOVERNANCE_VARS)'

governance-validate: ## Prove the access controls, by querying as each persona
	uv run python scripts/validate_governance.py --tf-dir $(TF_DIR)

governance-destroy: ## Tear down the GCP stack (demo projects only)
	cd $(TF_DIR) && terraform destroy -input=false

dq-report: ## Run the Dataplex data quality scans and print the results
	uv run python scripts/dataplex_report.py --tf-dir $(TF_DIR) --run

verify-cloud: ## Full cloud pipeline + proof, from an empty project
	# TWO Terraform applies, deliberately. A Dataplex data scan cannot be created against a table
	# that does not exist yet ("The source BigQuery table of the data scan is not found"), and the
	# Gold tables are created by dbt -- which needs the datasets and policy tags the first apply
	# produces. So the dependency genuinely runs infra -> data -> infra. Splitting it into two
	# applies is honest about that; pretending one apply suffices means a stack that only works on
	# a project where the tables already happen to exist.
	$(MAKE) governance-apply
	$(MAKE) bq-data
	$(MAKE) governance-build
	$(MAKE) governance-apply
	$(MAKE) governance-validate
	$(MAKE) dq-report
	@echo "Cloud verification complete: built, governed, and validated."

# ---------------------------------------------------------------------------------------------
# Spark, streaming, contracts, metrics
# ---------------------------------------------------------------------------------------------
spark-test: ## Run the Spark framework tests (incl. a real local Spark session)
	cd spark && uv run --with pyspark==3.5.1 --with pyyaml --with pytest python -m pytest tests -q

spark-validate: ## Validate every Spark job spec without touching GCP
	@for f in spark/jobs/*.yaml spark/jobs/generated/*.yaml; do \
		cd spark && uv run --with pyyaml python -m framework.main --config "../$$f" --validate-only && cd ..; \
	done

topics-check: ## Fail if the generated Kafka offload jobs are stale vs the topic registry
	uv run --with pyyaml python streaming/generate_topic_jobs.py --check

contracts-check: ## Run the data contract compatibility tests
	cd services/contract-api && uv run --with pytest --with pyyaml --with fastapi --with httpx python -m pytest tests -q

lineage-check: ## Column lineage from the compiled SQL, and the personal-data checks built on it
	$(DBT) compile $(DBT_DIRS) --target $(TARGET) --quiet
	$(DBT) docs generate $(DBT_DIRS) --target $(TARGET) --quiet
	uv run python -m pytest lineage/tests -q
	uv run python -m lineage.cli pii

privacy-test: ## Erasure tests, including a real Iceberg table (downloads the runtime on first run)
	uv run --with "pyspark==3.5.1" python -m pytest privacy/tests -q

erasure-check: ## Every topic can satisfy an erasure request (CI gate)
	uv run python -m privacy.cli check-topics

erasure-deadlines: ## Age of every open request; non-zero exit while one still needs action
	uv run python -m privacy.cli deadlines --warn-days 21

erasure-sweep: ## Process pending erasure requests (DRY_RUN=1 to see it without doing it)
	uv run python -m privacy.cli sweep $(if $(DRY_RUN),--dry-run,)
	uv run python -m privacy.cli verify-all

metrics: ## DORA-style engineering metrics from git history
	uv run python scripts/dora_metrics.py --days 90

clean: ## Remove the local DuckDB file and dbt artefacts
	rm -f $(DUCKDB_PATH) data/*.duckdb data/*.duckdb.wal
	rm -rf dbt/target dbt/dbt_packages dbt/logs
