{#
    Resolve semantic PII classifications into BigQuery policy tags at build time.

    Design
    ------
    A policy tag id looks like:
        projects/<project>/locations/<region>/taxonomies/<numeric-id>/policyTags/<numeric-id>

    Those ids are generated by Terraform and differ per environment, so hard-coding them in schema
    YAML would couple every model to one project. Instead each sensitive column declares *what the
    data is*:

        - name: email
          meta: { pii_class: contact }

    and the platform supplies *what that classification means here*, via the `policy_tag_ids` var:

        policy_tag_ids: {contact: "projects/.../policyTags/123", ...}

    The classification is reviewable in code review by an analytics engineer who knows the data; the
    taxonomy id is an infrastructure detail injected by `scripts/governance_vars.py` from
    `terraform output`. Neither side needs to know the other's business.

    Mechanism
    ---------
    dbt-bigquery sends policy tags as part of the column-level `persist_docs` schema patch (there is
    no BigQuery DDL for setting a policy tag). Overriding `bigquery__alter_column_comment` therefore
    puts the resolution on exactly the code path that already writes column metadata -- no extra API
    call, and it runs on every model build, so tags are reapplied after a full refresh.
#}

{% macro resolve_policy_tags(column_dict) %}
    {%- set tag_ids = var('policy_tag_ids', {}) -%}
    {%- set require = (var('require_policy_tags', false) | string | lower == 'true') -%}
    {%- set resolved = {} -%}

    {%- for column_name, column in column_dict.items() -%}
        {%- set meta = column.get('meta') or {} -%}
        {%- set pii_class = meta.get('pii_class') -%}
        {%- set tag = tag_ids.get(pii_class) if pii_class else none -%}

        {%- if pii_class and not tag -%}
            {%- set message = "Column '" ~ column_name ~ "' declares pii_class '" ~ pii_class
                ~ "' but no policy tag id is configured for it in the `policy_tag_ids` var. "
                ~ "The column would be published without column-level security." -%}
            {%- if require -%}
                {{ exceptions.raise_compiler_error(message) }}
            {%- else -%}
                {% do exceptions.warn(message ~ " Continuing because `require_policy_tags` is false.") %}
            {%- endif -%}
        {%- endif -%}

        {#- update_columns() only reads `description` and `policy_tags`, so a minimal dict is enough
            and avoids copying dbt's ColumnInfo structure. -#}
        {%- do resolved.update({
            column_name: {
                'name': column_name,
                'description': column.get('description'),
                'policy_tags': [tag] if tag else []
            }
        }) -%}
    {%- endfor -%}

    {{ return(resolved) }}
{% endmacro %}


{#- Override: same behaviour as dbt-bigquery's, with pii_class resolution spliced in. -#}
{% macro bigquery__alter_column_comment(relation, column_dict) -%}
    {% do adapter.update_columns(relation, resolve_policy_tags(column_dict)) %}
{% endmacro %}
