"""Turn `terraform output` into the dbt `--vars` payload for the governance stack.

Why this script exists
----------------------
Policy tag ids and service account emails are generated by Terraform and differ per environment.
Hard-coding them in dbt would couple every model to one GCP project; hand-copying them after each
apply is the kind of manual step that is skipped exactly once, on the day it matters.

So the handoff is mechanical:

    terraform output  ──▶  this script  ──▶  dbt --vars '{...}'

dbt models declare *semantics* (`meta.pii_class: contact`); Terraform declares *identity*
(`contact = projects/.../policyTags/123`); this joins them. Neither side has to know the other's
naming, and an environment can be rebuilt from scratch without touching a model file.

Usage
-----
    python scripts/governance_vars.py --tf-dir terraform/envs/dev            # JSON to stdout
    dbt build --vars "$(python scripts/governance_vars.py)"                  # inline into a run
    python scripts/governance_vars.py --format env                           # shell exports
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys

DEFAULT_TF_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "terraform", "envs", "dev")


def terraform_output(tf_dir: str) -> dict:
    """Read all outputs from a Terraform root as plain Python values."""
    binary = shutil.which("terraform")
    if binary is None:
        sys.exit("terraform not found on PATH")
    if not os.path.isdir(tf_dir):
        sys.exit(f"no such Terraform directory: {tf_dir}")

    result = subprocess.run(
        [binary, "output", "-json"],
        cwd=tf_dir,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.exit(f"terraform output failed in {tf_dir}:\n{result.stderr.strip()}")

    raw = json.loads(result.stdout or "{}")
    if not raw:
        sys.exit(f"{tf_dir} has no outputs -- has it been applied?")
    return {key: entry["value"] for key, entry in raw.items()}


def build_vars(outputs: dict, require_policy_tags: bool) -> dict:
    """Assemble exactly the vars dbt_project.yml declares, and nothing else."""
    missing = [k for k in ("policy_tag_ids", "row_access_policies") if k not in outputs]
    if missing:
        sys.exit(f"Terraform outputs are missing {missing}. Is this the governance root?")

    return {
        "policy_tag_ids": outputs["policy_tag_ids"],
        "row_access_policies": outputs["row_access_policies"],
        # Fail the dbt run if a model declares a pii_class this environment has no tag for, rather
        # than publishing the column unprotected. Off by default only for local DuckDB work.
        "require_policy_tags": require_policy_tags,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--tf-dir", default=DEFAULT_TF_DIR, help="Terraform root to read outputs from")
    parser.add_argument(
        "--format",
        choices=["json", "env"],
        default="json",
        help="json: a --vars payload. env: shell exports of project/region/dataset/persona values.",
    )
    parser.add_argument(
        "--no-require-policy-tags",
        action="store_true",
        help="Do not fail the dbt run when a declared pii_class has no configured tag id.",
    )
    args = parser.parse_args()

    outputs = terraform_output(args.tf_dir)

    if args.format == "json":
        print(json.dumps(build_vars(outputs, not args.no_require_policy_tags)))
        return

    exports = {
        "GCP_PROJECT": outputs.get("project_id", ""),
        "BQ_LOCATION": outputs.get("region", ""),
        "BQ_DATASET": outputs.get("dataset_ids", {}).get("marts", "marts"),
        "BQ_RAW_DATASET": outputs.get("dataset_ids", {}).get("raw", "raw"),
    }
    for key, email in outputs.get("persona_emails", {}).items():
        exports[f"PERSONA_{key.upper()}"] = email
    for key, value in exports.items():
        print(f"export {key}={value!r}")


if __name__ == "__main__":
    main()
